[package]
name = "magic_dragon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.4"
ndarray_einsum_beta = "0.7.0"
rand = "0.3.15"